### ISSUE TITLE
Implement basic endpoints from the realworld API

### ISSUE THREAD

**Issue by colinbankier** [colinbankier/realworld-tide#1]
Implement endpoints from https://github.com/gothinkster/realworld/tree/master/api
Implementation details, application structure, etc can be refactored/improved later.

**Comment by oddg** [comment]
This is the current state of the app in this regard
- [x] User resource
  - [x] `POST /api/users/login`
  - [x] `POST /api/users`
  - [x] `GET /api/user`
  - [x] `PUT /api/user`
- [x] Profile resource
  - [x] `GET /api/profiles/:username`
  - [x] `POST /api/profiles/:username/follow`
  - [x] `DELETE /api/profiles/:username/follow`
- [x] Article resource
  - [x] `GET /api/articles`
  - [x] `GET /api/articles/feed`
  - [x] `GET /api/articles/:slug`
  - [x] `POST /api/articles`
  - [x] `PUT /api/articles/:slug`
  - [x] `DELETE /api/articles/:slug`
  - [x] `POST /api/articles/:slug/comments`
  - [x] `GET /api/articles/:slug/comments`
  - [x] `DELETE /api/articles/:slug/comments/:id`
  - [x] `POST /api/articles/:slug/favorite`
  - [x] `DELETE /api/articles/:slug/favorite`
- [x] Tag resource
  - [x] `GET /api/tags`

**Comment by LukeMathWalker** [comment]
We can close this one - the spec has been fully implemented.

**Comment by colinbankier** [comment]
Confirming all tests in the realworld api tests pass :+1:
