### ISSUE TITLE
How to work with front end

### ISSUE THREAD

**Issue by gihrig** [colinbankier/realworld-tide#24]
Hello!
I'm trying to pair realworld-tide back end with [seed-rs-realworld](https://github.com/seed-rs/seed-rs-realworld) front end.

(edit 1)
I'm posting here because I believe it's ultimately a back end problem. I'm guessing there's something not covered by the realworld Postman tests that the "official" back end is doing. So it's really more of a realworld/Postman error, but it will need to be fixed in the back end. I have tried several back end/front end combinations and I'm getting similar problems.

---

I'm getting errors when creating a new article. The error appears in the UI as "data error" when a new article is saved. After that loading the feed gets "error loading feed" and the user's page gets "error loading profile"

seed-rs-realworld works as expected when connecting to `https://conduit.productionready.io/api` but exhibits the error when connecting to realworld-tide `http://localhost:5000/api`.

realworld-tide works as expected when following the README instructions, including the 'realworld Postman' tests.

Can anyone provide a clue as to what I need to do to get these two projects working together?

(edit 1)
macOS 10.14.6
rustc 1.43.0-nightly (58b834344 2020-02-05)

I have compared the 'conversation' between front end and back end, when the locally installed front end is communicating to realworld-tide `BASE_API_URL: &str = "http://localhost:5000/api";` vs `BASE_API_URL: &str = "https://conduit.productionready.io/api";` and they are very different.

Screen shots of browser/server conversation from Brave dev tools > Network
![image](https://user-images.githubusercontent.com/1481063/76736896-f67b9800-6724-11ea-9b4e-4f1cdeff71c9.png)
![image](https://user-images.githubusercontent.com/1481063/76736969-17dc8400-6725-11ea-8e69-a539167dd7c1.png)
![image](https://user-images.githubusercontent.com/1481063/76737018-3cd0f700-6725-11ea-94fa-cc9f2594eab2.png)

Error messages from Brave dev tools > Console
On saving a new article:
<pre>
package.js:311 "App error:" SerdeError(
    Error("invalid type: null, expected a string", line: 1, column: 257),
    "{\"article\":{\"title\":\"Title\",\"slug\":\"title\",\"description\":\"About\",\"body\":\"Article\",\"favorited\":false,\"favoritesCount\":0,\"createdAt\":\"2020-03-16T21:21:17.436566Z\",\"updatedAt\":\"2020-03-16T21:21:17.436566Z\",\"author\":{\"username\":\"user_99\",\"bio\":null,\"image\":null,\"following\":false},\"tagList\":[\"tag\"]}}",
)
imports.wbg.__widl_f_error_1_ @ package.js:311
</pre>

On loading Home page after creating a new article
<details>
<summary>
<pre>
package.js:311 "App error:" SerdeError(
    Error("invalid type: null, expected a string", line: 1, column: 56),
    "{\"profile\":{\"username\":\"user_99\",\"bio\":null,\"image\":null,\"following\":true}}",
)
imports.wbg.__widl_f_error_1_ @ package.js:311
</pre>
</summary>
<pre>
web_sys::console::error_1::hd2304b958289b375
seed::shortcuts::error_1::h795ba69c96d09b13
seed_rs_realworld::logger::error::hfdad8a7dd223d8ee
seed_rs_realworld::request::fail_reason_into_errors::h88de7af1ec1a8860
core::ops::function::FnOnce::call_once::h9468d7274cc2b019
core::result::Result<T,E>::map_err::hde07a9bd2a8aa36f
seed_rs_realworld::request::author::load::{{closure}}::{{closure}}::hf687013463b55396
seed::browser::service::fetch::Request::fetch_json_data::{{closure}}::hd634cf92ebc22db0
seed::browser::service::fetch::Request::fetch_json::{{closure}}::h96cc17521fa07754
<std::future::GenFuture<T> as core::future::future::Future>::poll::he6bb125c99447a38
std::future::poll_with_tls_context::h17d72644f5af33a6
seed_rs_realworld::request::author::load::{{closure}}::he1b4ff429e1dadd8
<std::future::GenFuture<T> as core::future::future::Future>::poll::h76c1c46d9e7c94a8
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::hb75405b9126432c9
std::future::poll_with_tls_context::h45e211ba5af37edc
<seed::app::effects::Effect<Ms,GMs> as seed::app::message_mapper::MessageMapper<Ms,OtherMs>>::map_msg::{{closure}}::hff7c6cdcaa6d9347
<std::future::GenFuture<T> as core::future::future::Future>::poll::h8e0190c99ed0edaa
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h63df8d21c2dd5ef0
std::future::poll_with_tls_context::h61c2dd34ded147a5
seed::app::App<Ms,Mdl,ElC,GMs>::process_queue_cmd::{{closure}}::{{closure}}::h1abb9a94d1b68861
<std::future::GenFuture<T> as core::future::future::Future>::poll::h1580ef5170d0aafe
wasm_bindgen_futures::task::singlethread::Task::run::he239f50cc6644636
wasm_bindgen_futures::queue::QueueState::run_all::h9ca3271c5ce12f35
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h83d5eef61991488c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_b6fef331fde5cf0a @ package.js:1468
js_sys::Promise::then::h108b3d034ca6944d
wasm_bindgen_futures::queue::Queue::push_task::h6614b9c6b7faaef7
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::hdd4578778e8732db
std::thread::local::LocalKey<T>::try_with::h13b7c994bc71d856
std::thread::local::LocalKey<T>::with::h4d6878423d07d4a3
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::h294849a6f4ed7a0e
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h82e25a18a6f42100
core::task::wake::Waker::wake::h705fe2d02f33618d
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::h868f31e4a22e774c
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::{{closure}}::hca83fca129a28074
core::ops::function::FnOnce::call_once::h9dfefa1b7e4bf3bf
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hc34773fbf5e66186
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_7d828a330efec051 @ package.js:1476
js_sys::Promise::then2::h4d71ecd151371c38
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h76e5dae08fe19bd5
seed::browser::service::fetch::Request::fetch_string::{{closure}}::he8e308ad1b785f1b
<std::future::GenFuture<T> as core::future::future::Future>::poll::h07dbe87f7d4a168e
std::future::poll_with_tls_context::hdadc89bbf5ac12ea
seed::browser::service::fetch::Request::fetch_json::{{closure}}::h96cc17521fa07754
<std::future::GenFuture<T> as core::future::future::Future>::poll::he6bb125c99447a38
std::future::poll_with_tls_context::h17d72644f5af33a6
seed_rs_realworld::request::author::load::{{closure}}::he1b4ff429e1dadd8
<std::future::GenFuture<T> as core::future::future::Future>::poll::h76c1c46d9e7c94a8
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::hb75405b9126432c9
std::future::poll_with_tls_context::h45e211ba5af37edc
<seed::app::effects::Effect<Ms,GMs> as seed::app::message_mapper::MessageMapper<Ms,OtherMs>>::map_msg::{{closure}}::hff7c6cdcaa6d9347
<std::future::GenFuture<T> as core::future::future::Future>::poll::h8e0190c99ed0edaa
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h63df8d21c2dd5ef0
std::future::poll_with_tls_context::h61c2dd34ded147a5
seed::app::App<Ms,Mdl,ElC,GMs>::process_queue_cmd::{{closure}}::{{closure}}::h1abb9a94d1b68861
<std::future::GenFuture<T> as core::future::future::Future>::poll::h1580ef5170d0aafe
wasm_bindgen_futures::task::singlethread::Task::run::he239f50cc6644636
wasm_bindgen_futures::queue::QueueState::run_all::h9ca3271c5ce12f35
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h83d5eef61991488c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_b6fef331fde5cf0a @ package.js:1468
js_sys::Promise::then::h108b3d034ca6944d
wasm_bindgen_futures::queue::Queue::push_task::h6614b9c6b7faaef7
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::hdd4578778e8732db
std::thread::local::LocalKey<T>::try_with::h13b7c994bc71d856
std::thread::local::LocalKey<T>::with::h4d6878423d07d4a3
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::h294849a6f4ed7a0e
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h82e25a18a6f42100
core::task::wake::Waker::wake::h705fe2d02f33618d
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::h868f31e4a22e774c
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::{{closure}}::hca83fca129a28074
core::ops::function::FnOnce::call_once::h9dfefa1b7e4bf3bf
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hc34773fbf5e66186
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_7d828a330efec051 @ package.js:1476
js_sys::Promise::then2::h4d71ecd151371c38
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h76e5dae08fe19bd5
seed::browser::service::fetch::Request::send_request::{{closure}}::h0bfaded3fe60d863
<std::future::GenFuture<T> as core::future::future::Future>::poll::h0980b5ae00beb7b3
std::future::poll_with_tls_context::hbb2729760a0d8c65
seed::browser::service::fetch::Request::fetch::{{closure}}::h160df8087b184799
<std::future::GenFuture<T> as core::future::future::Future>::poll::h304af1d89be250cd
std::future::poll_with_tls_context::h5e508185ac056aa2
seed::browser::service::fetch::Request::fetch_string::{{closure}}::he8e308ad1b785f1b
<std::future::GenFuture<T> as core::future::future::Future>::poll::h07dbe87f7d4a168e
std::future::poll_with_tls_context::hdadc89bbf5ac12ea
seed::browser::service::fetch::Request::fetch_json::{{closure}}::h96cc17521fa07754
<std::future::GenFuture<T> as core::future::future::Future>::poll::he6bb125c99447a38
std::future::poll_with_tls_context::h17d72644f5af33a6
seed_rs_realworld::request::author::load::{{closure}}::he1b4ff429e1dadd8
<std::future::GenFuture<T> as core::future::future::Future>::poll::h76c1c46d9e7c94a8
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::hb75405b9126432c9
std::future::poll_with_tls_context::h45e211ba5af37edc
<seed::app::effects::Effect<Ms,GMs> as seed::app::message_mapper::MessageMapper<Ms,OtherMs>>::map_msg::{{closure}}::hff7c6cdcaa6d9347
<std::future::GenFuture<T> as core::future::future::Future>::poll::h8e0190c99ed0edaa
<futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h63df8d21c2dd5ef0
std::future::poll_with_tls_context::h61c2dd34ded147a5
seed::app::App<Ms,Mdl,ElC,GMs>::process_queue_cmd::{{closure}}::{{closure}}::h1abb9a94d1b68861
<std::future::GenFuture<T> as core::future::future::Future>::poll::h1580ef5170d0aafe
wasm_bindgen_futures::task::singlethread::Task::run::he239f50cc6644636
wasm_bindgen_futures::queue::QueueState::run_all::h9ca3271c5ce12f35
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h83d5eef61991488c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_b6fef331fde5cf0a @ package.js:1468
js_sys::Promise::then::h108b3d034ca6944d
wasm_bindgen_futures::queue::Queue::push_task::h6614b9c6b7faaef7
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::hdd4578778e8732db
std::thread::local::LocalKey<T>::try_with::h13b7c994bc71d856
std::thread::local::LocalKey<T>::with::h4d6878423d07d4a3
wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::h294849a6f4ed7a0e
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h82e25a18a6f42100
core::task::wake::Waker::wake::h705fe2d02f33618d
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::h868f31e4a22e774c
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::{{closure}}::hca83fca129a28074
core::ops::function::FnOnce::call_once::h9dfefa1b7e4bf3bf
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hc34773fbf5e66186
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h588d9119818916c3
__wbg_adapter_31 @ package.js:229
real @ package.js:1621
Promise.then (async)
imports.wbg.__wbg_then_7d828a330efec051 @ package.js:1476
js_sys::Promise::then2::h4d71ecd151371c38
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h76e5dae08fe19bd5
seed::browser::next_tick::NextTick::new::hd116adc2ea06aaa7
seed::app::App<Ms,Mdl,ElC,GMs>::process_queue_cmd::h59f6d82f93710bb2
seed::app::App<Ms,Mdl,ElC,GMs>::process_cmd_and_msg_queue::h977eaec98aeed0ed
seed::app::App<Ms,Mdl,ElC,GMs>::update::hc183116e14256281
seed::app::App<Ms,Mdl,ElC,GMs>::run::{{closure}}::h888e916fd6e8b388
seed::browser::service::routing::setup_link_listener::{{closure}}::{{closure}}::hf0c1eff164dba8d2
core::option::Option<T>::map::h894ce16a0c08b94c
seed::browser::service::routing::setup_link_listener::{{closure}}::hdfba4d0248845122
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9b77e1a31ef9cfdc
__wbg_adapter_22 @ package.js:211
real @ package.js:1598
</pre>
</details>

Thanks for creating this _awesome_ project! I'm really excited to get it working and learning from it. Your work is _very much_ appreciated :-)

**Comment by LukeMathWalker** [comment]
Hey!
I can have a look later during the week :grin:

**Comment by gihrig** [comment]
Thanks! I'll keep working on it and update here as I find things.

**Comment by gihrig** [comment]
Digging through the comparison between the non-working and working headers I noticed there are actually null values being returned from the back end server:
<pre>
package.js:311 "App error:" SerdeError(
    Error("invalid type: null, expected a string"...),
    "{...,\"bio\":null,\"image\":null,\"...}",
)
</pre>
 And indeed, user `image` and user `bio` are empty when a new user is created. For some reason this is not a problem when working against the realworld demo back end server.

So I tried adding these values in my local setup. That failed with a CORS error in the browser console:
![image](https://user-images.githubusercontent.com/1481063/76829903-71a28400-67e1-11ea-86ae-8989b3e77d32.png)

Looking for CORS in the earlier header data I find this:
![image](https://user-images.githubusercontent.com/1481063/76830083-c645ff00-67e1-11ea-8526-fd683275004a.png)

Seems reasonable to me that `same-site` might fail (`localhost:8000` is a different site than `localhost:5000`?) Where `cross-site` would work. A bit of brief searching through code did not turn up a means to change this header.

I'm not really up on CORS config, much less on how it's done in these (front end and back end) apps, but that will be my next point of investigation.

Does it seem appropriate that this should be an issue when working strictly on `localhost`?

**Comment by LukeMathWalker** [comment]
Some verbs were indeed missing from our CORS middleware - can you run against https://github.com/colinbankier/realworld-tide/pull/25 and check if it works?

**Comment by gihrig** [comment]
@LukeMathWalker #25 fixes the profile update failure - Thanks for that!

The original error which I can now summarize as "Null returned in some fields crashes front end" still remains. With #25 in place, that error can be successfully worked around by manually ensuring there are no empty fields in the user profile.

Would you suggest opening a new issue for this?

The 'official' realworld demo back end returns an empty string `""` for empty fields. This would eliminate the original issue.

If you could point me in right direction (file) I would be happy to open a PR for this.

Thanks again for your attention to this issue. You got me 'un-stuck'! Thanks! :-)

**Comment by LukeMathWalker** [comment]
To be honest I think the front-end should handle `null` for those fields, because they are indeed optional. An empty bio and a missing bio are not the same thing for me :thinking:

**Comment by gihrig** [comment]
> An empty bio and a missing bio are not the same thing for me

Agreed. A missing field would be an error, whereas an empty field _could_ be a normal condition on new record creation.

In this case, `bio` and `image` are empty, not missing so I would think and empty string would be the appropriate value. Regardless of that, this is the behavior of the 'official' realworld demo back end that all the realworld front ends work with. So, while I certainly can work with it either way, the realworld projects do not expect a null value.

(edit)
In the above I was considering the output from the back end after a new user account had been created. Looking at the picture from the viewpoint of the data proved by the front end to the back end when a new user account is created, `bio` and `image` are truly missing.

<pre>
{"user":{"username":"user_86","email":"86@smart.com","password":"user_86pw"}}
</pre>

This does seem like an error since the front end expects non-null values in return.

I'm happy with the solution you provided. 

Thanks for that! 🎉

This issue can be closed.
