### ISSUE TITLE
Problem starting the app

### ISSUE THREAD

**Issue by azzamsa** [colinbankier/realworld-tide#28]
I've followed the [setup steps](https://github.com/colinbankier/realworld-tide#setup), but still have problem.

1. I've installed diesel
2. executed `./scripts/init_db.sh`

But I get error massage "app can't connect to port ", so I made changes:

```diff
modified   configuration/development.yml
@@ -1,4 +1,4 @@
 application:
   host: localhost
 database:
-  port: 5433
+  port: 5432
```

Now I get this message:

``` bash
[2020-08-14T23:30:53Z ERROR r2d2] FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

[2020-08-14T23:30:53Z ERROR r2d2] FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

[2020-08-14T23:30:53Z ERROR r2d2] FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
```

the default password defined by [`init_db.sh`](https://github.com/colinbankier/realworld-tide/blob/master/scripts/init_db.sh#L8) should be "password". But why this error happend?

**Comment by azzamsa** [comment]
I works after I changed the default password. This is my all diff.

```diff

Unstaged changes (4)
modified   configuration/base.yml
@@ -3,9 +3,9 @@ application:
   port: 5000
 database:
   host: localhost
-  port: 5432
+  port: 5434
   username: postgres
-  password: password
+  password: 123456
   db: realword
 authentication:
   secret: asupersecretsecret
modified   configuration/development.yml
@@ -1,4 +1,4 @@
 application:
   host: localhost
 database:
-  port: 5433
+  port: 5434
modified   scripts/init_db.sh
@@ -5,7 +5,7 @@ set -eo pipefail
 # Check if a user has been set, otherwise default to 'postgres'
 DB_USER=${POSTGRES_USER:=postgres}
 # Check if a password has been set, otherwise default to 'password'
-DB_PASSWORD="${POSTGRES_PASSWORD:=password}"
+DB_PASSWORD="${POSTGRES_PASSWORD:=123456}"
 # Check if a password has been set, otherwise default to 'realworld'
 DB_NAME="${POSTGRES_DB:=realword}"
 # Check if a port has been set, otherwise default to '5434'
```

---

now still looking for correct endpoints :)

The app is running well:

![image](https://user-images.githubusercontent.com/17734314/90302985-4a58fb80-ded4-11ea-95f0-dbffa64de176.png)

![image](https://user-images.githubusercontent.com/17734314/90302979-44631a80-ded4-11ea-9774-b7f6af69705e.png)

but endpoints not found: (maybe I need to search the correct path)

![image](https://user-images.githubusercontent.com/17734314/90302926-ef270900-ded3-11ea-9e3a-e023cba6d085.png)

**Comment by colinbankier** [comment]
Thanks - it's not clear why the password would matter, but I'll run through the steps on a clean checkout to ensure it works as described. It may be more likely that the port was the issue, which is different between test / development dbs - the readme does include setting the env var to set this, e.g. `POSTGRES_PORT=5433 ./scripts/init_db.sh` for running in dev mode.

Also, your URL doesn't look right - routes are scoped under `/api/`, so try `/api/users/`. The realworld test suit passes for all routes if run as per the readme.

**Comment by azzamsa** [comment]
> Also, your URL doesn't look right - routes are scoped under `/api/`, so try `/api/users/`. The realworld test suit passes for all routes if run as per the readme.

Oh, I don't see the `/api/` in the postman collections. Solved, thanks.
