### ISSUE TITLE
Setup CI integration

### ISSUE THREAD

**Issue by colinbankier** [colinbankier/realworld-tide#3]
TravisCI, CircleCI and a host of others offer free tiers - choose one, and integrate it with the project.

**Comment by oddg** [comment]
Hi @colinbankier! Really sweet project.

I gathered from #8 that you would not mind external contributions.
I am [working](https://github.com/oddg/realworld-tide/pull/2) on the CI. Here my plan:
- [x] get the app to compile
- [x] add basic CI to run `cargo build`
- [x] get the test to compile and pass (thanks to @LukeMathWalker)
- ~[ ] add a `cargo make t` in the travis file~  (thanks to @LukeMathWalker)
- [x] add extra validation:
  - `cargo fmt`
  - `cargo clippy`
  - ~`cargo audit`~ (vulnerability in `tokio` dependency)

**Comment by LukeMathWalker** [comment]
It would cool to add `cargo audit` to the CI pipeline as well, if we want to keep as close as possible to a real world application.

**Comment by colinbankier** [comment]
This is great, thanks! The existing cargo make file used to compile and run
tests successfully, but after changes in tide things broke. Are you hoping
to update to latest tide as part of this? I'll have to review what state I
left things in last time I tried to update.

**Comment by oddg** [comment]
> Are you hoping to update to latest tide as part of this?

I tried to build with tide v0.2 and the build breaks because tide v0.2 depends on http-service v0.2.0 which does not compile anymore (it uses the removed `await!` macro).

So yes for now I am targeting the master branch of tide. Maybe we could target a specific commit to have a bit more stability.

**Comment by LukeMathWalker** [comment]
I have opened a PR ( https://github.com/oddg/realworld-tide/pull/3 ) against your branch @oddg to simplify the setup of the database and remove `cargo-make` as a dependency/added complexity.

**Comment by oddg** [comment]
`cargo audit` reports a vulnerability related to [`memoffset`](https://github.com/Gilnaa/memoffset/issues/24) which is an indirect dependency of `tokio-threadpool`. Not too sure what we can do about it.

**Comment by LukeMathWalker** [comment]
> `cargo audit` reports a vulnerability related to [`memoffset`](https://github.com/Gilnaa/memoffset/issues/24) which is an indirect dependency of `tokio-threadpool`. Not too sure what we can do about it.

It's enough to run `cargo update` and commit the new `Cargo.lock` to version control. I have opened a PR with the output: https://github.com/oddg/realworld-tide/pull/5
Cargo audit comes out clean now :+1:
