### ISSUE TITLE
Setup up linting, format checks, coverage checks for CI

### ISSUE THREAD

**Issue by colinbankier** [colinbankier/realworld-tide#4]
Related to #3 , set up basic quality checks including test coverage and rustfmt. Investigate other good checks, e.g. linting, for rust.

**Comment by LukeMathWalker** [comment]
Given #10, I'd say that the only thing we are missing right now is code coverage, right?

**Comment by colinbankier** [comment]
Yep, I think so. I've started #12  to cover this.

**Comment by azzamsa** [comment]
is this issue still relevant? #12 is merged.

**Comment by colinbankier** [comment]
You're right, this is done already. Closing.
