### ISSUE TITLE
Contributors?

### ISSUE THREAD

**Issue by LukeMathWalker** [colinbankier/realworld-tide#8]
Hi @colinbankier!

I was looking for an opportunity to get some mileage using `tide` for a not-too-trivial application and I was about to start working on RealWord when I found out your repo!
Would you be interested in PRs to finish the job here, or do you see this as more of a personal exercise?

Fine with both, just wanted to understand your stance before moving in a direction or another :+1:

**Comment by colinbankier** [comment]
Hi! I certainly started this hoping to get contributors and evolve it as a
solid realworld tide example. It got stalled as tide was undergoing major
changes - so I paused working on it temporarily.
Totally happy to accept contributions and add colaborators to help keep it
moving forward.

**Comment by LukeMathWalker** [comment]
Awesome :star:
